### ISSUE TITLE
Tests not passing

### ISSUE THREAD

**Issue by ilanschnell** [boppreh/aes#6]
Using master (with Python 3.5, 3.7 or 3.8) I get:
```
$ python tests.py 
........FFFF.FFFF..........FFFF......
======================================================================
FAIL: test_different_iv (__main__.TestCfb)
Different IVs should generate different ciphertexts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 223, in test_different_iv
    plaintext1 = self.aes.decrypt_cfb(ciphertext1, self.iv)
  File "/Users/ilan/tmp/aes/aes.py", line 379, in decrypt_cfb
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_long_message (__main__.TestCfb)
CBC should allow for messages longer than a single block.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 239, in test_long_message
    self.assertEqual(self.aes.decrypt_cfb(ciphertext, self.iv), long_message)
  File "/Users/ilan/tmp/aes/aes.py", line 375, in decrypt_cfb
    plaintext_block = xor_bytes(ciphertext_block, self.decrypt_block(prev_ciphertext))
  File "/Users/ilan/tmp/aes/aes.py", line 252, in decrypt_block
    assert len(ciphertext) == 16
AssertionError

======================================================================
FAIL: test_single_block (__main__.TestCfb)
Should be able to encrypt and decrypt single block messages.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 196, in test_single_block
    self.assertEqual(self.aes.decrypt_cfb(ciphertext, self.iv), self.message)
  File "/Users/ilan/tmp/aes/aes.py", line 379, in decrypt_cfb
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_whole_block_padding (__main__.TestCfb)
When len(message) == block size, padding will add a block.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 233, in test_whole_block_padding
    self.assertEqual(self.aes.decrypt_cfb(ciphertext, self.iv), block_message)
  File "/Users/ilan/tmp/aes/aes.py", line 375, in decrypt_cfb
    plaintext_block = xor_bytes(ciphertext_block, self.decrypt_block(prev_ciphertext))
  File "/Users/ilan/tmp/aes/aes.py", line 252, in decrypt_block
    assert len(ciphertext) == 16
AssertionError

======================================================================
FAIL: test_different_iv (__main__.TestCtr)
Different IVs should generate different ciphertexts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 337, in test_different_iv
    plaintext1 = self.aes.decrypt_ctr(ciphertext1, self.iv)
  File "/Users/ilan/tmp/aes/aes.py", line 453, in decrypt_ctr
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_long_message (__main__.TestCtr)
CBC should allow for messages longer than a single block.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 353, in test_long_message
    self.assertEqual(self.aes.decrypt_ctr(ciphertext, self.iv), long_message)
  File "/Users/ilan/tmp/aes/aes.py", line 453, in decrypt_ctr
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_single_block (__main__.TestCtr)
Should be able to encrypt and decrypt single block messages.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 310, in test_single_block
    self.assertEqual(self.aes.decrypt_ctr(ciphertext, self.iv), self.message)
  File "/Users/ilan/tmp/aes/aes.py", line 453, in decrypt_ctr
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_whole_block_padding (__main__.TestCtr)
When len(message) == block size, padding will add a block.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 347, in test_whole_block_padding
    self.assertEqual(self.aes.decrypt_ctr(ciphertext, self.iv), block_message)
  File "/Users/ilan/tmp/aes/aes.py", line 453, in decrypt_ctr
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_different_iv (__main__.TestOfb)
Different IVs should generate different ciphertexts.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 280, in test_different_iv
    plaintext1 = self.aes.decrypt_ofb(ciphertext1, self.iv)
  File "/Users/ilan/tmp/aes/aes.py", line 417, in decrypt_ofb
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_long_message (__main__.TestOfb)
CBC should allow for messages longer than a single block.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 296, in test_long_message
    self.assertEqual(self.aes.decrypt_ofb(ciphertext, self.iv), long_message)
  File "/Users/ilan/tmp/aes/aes.py", line 417, in decrypt_ofb
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_single_block (__main__.TestOfb)
Should be able to encrypt and decrypt single block messages.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 253, in test_single_block
    self.assertEqual(self.aes.decrypt_ofb(ciphertext, self.iv), self.message)
  File "/Users/ilan/tmp/aes/aes.py", line 417, in decrypt_ofb
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

======================================================================
FAIL: test_whole_block_padding (__main__.TestOfb)
When len(message) == block size, padding will add a block.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 290, in test_whole_block_padding
    self.assertEqual(self.aes.decrypt_ofb(ciphertext, self.iv), block_message)
  File "/Users/ilan/tmp/aes/aes.py", line 417, in decrypt_ofb
    return unpad(b''.join(blocks))
  File "/Users/ilan/tmp/aes/aes.py", line 166, in unpad
    assert all(p == padding_len for p in padding)
AssertionError

----------------------------------------------------------------------
Ran 37 tests in 0.287s

FAILED (failures=12)
```

**Comment by boppreh** [comment]
Tests are finally passing.
